import type { Metadata } from "next";
import { RootLayout } from "@/components/layouts/RootLayout";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps<"/">) {
  return <RootLayout>{children}</RootLayout>;
}
